[target.'cfg(target_os = "windows")']
rustflags = ["-C", "control-flow-guard=yes"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "relocation-model=pie", "-C", "link-arg=-Wl,-z,relro,-z,now"]

[alias]
xtask = "run --package xtask --"
